sonar.projectKey=incendios-valle
sonar.organization=rodrigo-munoz-catalan
sonar.projectName=Incendios Valle del Sol
sonar.sources=ec2/api,frontend/src
sonar.tests=ec2/api/tests,frontend/src/__tests__
sonar.python.coverage.reportPaths=ec2/api/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/tests/**,**/__tests__/**
